"""Add images field to messages

Revision ID: 772ec2a4a724
Revises: b2a38df44fe9
Create Date: 2025-07-25 09:44:24.582912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '772ec2a4a724'
down_revision: Union[str, None] = 'b2a38df44fe9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('images', sa.JSON(), nullable=True))
    # SQLite doesn't support ALTER COLUMN, so we skip the id column change
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'images')
    # ### end Alembic commands ###
