"""add_unique_constraint_chat_message_order

Revision ID: 8a7f82bd7da8
Revises: e4eec6607236
Create Date: 2025-07-25 15:19:51.031567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7f82bd7da8'
down_revision: Union[str, None] = 'e4eec6607236'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_chat_message_order', ['chat_id', 'message_order'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_constraint('uq_chat_message_order', type_='unique')
    # ### end Alembic commands ###
