"""Create message_images table and remove images column from messages

Revision ID: e4eec6607236
Revises: 772ec2a4a724
Create Date: 2025-07-25 10:02:33.618045

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e4eec6607236'
down_revision: Union[str, None] = '772ec2a4a724'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_images',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('data', sa.Text(), nullable=False),
    sa.Column('size', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # SQLite doesn't support ALTER COLUMN, skip the id column type change
    # op.alter_column('messages', 'id', existing_type=sa.INTEGER(), type_=sa.BigInteger(), nullable=False, autoincrement=True)
    op.drop_column('messages', 'images')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('images', sqlite.JSON(), nullable=True))
    # SQLite doesn't support ALTER COLUMN, skip the id column type change
    # op.alter_column('messages', 'id', existing_type=sa.BigInteger(), type_=sa.INTEGER(), nullable=True, autoincrement=True)
    op.drop_table('message_images')
    # ### end Alembic commands ###
